namespace Gley.Localization
{
	public enum WordIDs
	{
		GalleryUI_Hint = 27,
		GalleryUI_Title = 26,
		GoldNotEnoughUI_Hint = 20,
		GoldNotEnoughUI_Title = 19,
		GuideUI_ErrTipLabel = 31,
		GuideUI_TipLabel = 32,
		GuideUI_Title = 30,
		IntroductionUI_PropHint1 = 34,
		IntroductionUI_PropHint2 = 35,
		IntroductionUI_PropHint3 = 36,
		IntroductionUI_Title = 33,
		Loading_UI = 37,
		LoseUI_LevelText = 21,
		LoseUI_Restart = 23,
		LoseUI_TimeOutText = 22,
		LuckyReward_Hint = 29,
		LuckyReward_Title = 28,
		MainUI_GalleryBtn_text = 2,
		MainUI_HelpBtn_text = 3,
		MainUI_NoadBtn_text = 1,
		MainUI_PlayBtn_id = 0,
		MainUI_Shopbtn = 38,
		PauseUI_Continue = 12,
		PauseUI_Home = 13,
		PauseUI_MusicText = 11,
		PauseUI_Restart = 14,
		PauseUI_SoundText = 10,
		PauseUI_TitleText = 9,
		RebornUI_Hint = 16,
		RebornUI_Title = 15,
		RebortUI_Ad = 17,
		RebortUI_Close = 18,
		SetiingUI_Share = 8,
		SettingUI_Privacy = 5,
		SettingUI_rates = 7,
		SettingUI_Terms = 6,
		SettingUI_TitleText = 4,
		WinUI_LevelText = 24,
		WinUI_Next = 25,
	}
}